# This is a template for your secrets.toml file
# DO NOT commit this file with real secrets to your repository
# On Streamlit Cloud, add these secrets via the web interface

# OpenAI API key
OPENAI_API_KEY = "your-openai-api-key"

# Any other secrets your app needs can be added here 