[build]
builder = "NIXPACKS"
buildCommand = ""

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
