   # .github/workflows/ci.yml

   name: RAG Chatbot CI

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     build:

       runs-on: windows-latest

       steps:
       - uses: actions/checkout@v3

       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.8'

       - name: Install dependencies
         run: |
           python -m venv venv
           venv\Scripts\activate
           pip install --upgrade pip
           pip install -r requirements.txt

       - name: Run Unit Tests
         run: |
           venv\Scripts\activate
           pytest tests/test_rag_evaluation.py